### ISSUE TITLE
scroll in gls

### ISSUE THREAD

**Issue by xialvjun** [basarat/gls#11]
https://codesandbox.io/s/reverent-cdn-te2xm?fontsize=14

well, I know, it's not gls's bug. But can gls make scroll more compatible with flex container?

**Comment by basarat** [comment]
I suspect you want only the number portion to scroll and the remaining portion to stick. 

Solved : https://codesandbox.io/embed/glsscrollbug-tgcqg 
How : using `scroll:hidden` on elements that you don't want getting a scrollbar. 

I've actually called `overflow:hidden` as `somecChildWillScroll` in the past : https://github.com/typestyle/csstips/blob/2427f1a3faa2ecf417849195fee55f4ce82a7fbb/src/scroll.ts#L27 

But doing atoms as styles is much easier than properties on components. A lot more thought needed to go into gls and I chose to stay closer to `overflow` values for the `scroll` prop :rose:

**Comment by xialvjun** [comment]
Thanks and 🌹. And we can not add `overflow:hidden` to Component with overflow children automatically because user can use some third-party Component as children. 

We should add this as caveat in https://basarat.com/gls/principle-scrolling/: add `overflow:hidden` to parent component if the children is scrollable.

**Comment by basarat** [comment]
overflow scroll hidden default has its own risks. Eg content doesn’t fit on screen and you can’t scroll to it either. 

Opened so that I will add an example of disabling self scroll so that browsers trigger a child scroll 🌹

**Comment by basarat** [comment]
I'm finding a minimum reproduction pretty hard to reproduce. I'll leave this open for someone to provide a neat example that explain the idea and works. My failed attempt:

```ts
Example use case - Ensuring browser scrolls a child:

<Playground style={{overflow: 'hidden'}}>
  { /* this hidden ensures the child gets the scroll bar */ }
  <Horizontal height={100} scroll='hidden' style={{backgroundColor: "lightskyblue"}}>
    <Content style={{backgroundColor: 'limegreen'}}>
      Some content on left
    </Content>
    <Vertical height={100} scroll='vertical'>
      <div style={{backgroundColor: 'lightpink'}}>Lots of content to make it overflow</div>
      <div style={{backgroundColor: 'lightpink'}}>Lots of content to make it overflow</div>
      <div style={{backgroundColor: 'lightpink'}}>Lots of content to make it overflow</div>
      <div style={{backgroundColor: 'lightpink'}}>Lots of content to make it overflow</div>
      <div style={{backgroundColor: 'lightpink'}}>Lots of content to make it overflow</div>
      <div style={{backgroundColor: 'lightpink'}}>Lots of content to make it overflow</div>
      <div style={{backgroundColor: 'lightpink'}}>Lots of content to make it overflow</div>
      <div style={{backgroundColor: 'lightpink'}}>Lots of content to make it overflow</div>
      <div style={{backgroundColor: 'lightpink'}}>Lots of content to make it overflow</div>
      <div style={{backgroundColor: 'lightpink'}}>Lots of content to make it overflow</div>
      <div style={{backgroundColor: 'lightpink'}}>Lots of content to make it overflow</div>
      <div style={{backgroundColor: 'lightpink'}}>Lots of content to make it overflow</div>
      <div style={{backgroundColor: 'lightpink'}}>Lots of content to make it overflow</div>
    </Vertical>
  </Horizontal>
</Playground>
```

**Comment by basarat** [comment]
Closing as not really a gls issue as mentioned, and I like a backlog. Googling `Using overflow:hidden to ensure a child gets a scrollbar` might help for someone willing to tackle this :rose:
