### ISSUE TITLE
Any Changelog? Like why Flex is removed.

### ISSUE THREAD

**Issue by xialvjun** [basarat/gls#12]
Just as the title.

**Comment by basarat** [comment]
Sorry, added a note for future though: https://github.com/basarat/gls/commit/dcb97f0377668b73abafe1811531293c17d2bdb5 

Answer your question though: `Flex` is too ambiguous, so renamed to `Stretch`. People kept using `Flex` thinking they are buying into *flexbox* without realizing they are are actually controlling sub properties in flexbox css. This was conveyed internally to my team, but they aren't using this package directly so I didn't do the homework here :rose:
