### ISSUE TITLE
NextJS?

### ISSUE THREAD

**Issue by mikecann** [basarat/gls#15]
Hi Basrat, 

This is a fantastic lib and I use it for all my projects. I am just working on redoing my blog using NextJS and ofcourse im using GLS. 

Im having an issue however that seems to be causing a reflow. I think its caused by styles being embedded in the JS which is loaded late.

I noticed your Gist [here](https://gist.github.com/basarat/060bdf95ae8c46c62129f8c5b1bf4b88) 14 months ago, I tried to implement it but im still getting the reflow issue.

You can see what I mean by going to the build URL: https://next-mikecann.vercel.app/

You will see the page is rendered okay but you get a flicker once the JS loads, this is evident if you open the inspector:

![image](https://user-images.githubusercontent.com/215033/101483773-9f44e400-3993-11eb-8c8b-a51fb4741b05.png)

Im not sure whats causing this, do you know?

Incase you are interested the src is here: https://github.com/mikecann/next-mikecann

Cheers

**Comment by basarat** [comment]
Sorry for not replying earlier. PS: *You* can always hit me on twitter ;) :rose: 

I've updated the gist : https://gist.github.com/basarat/060bdf95ae8c46c62129f8c5b1bf4b88 with what I used for https://designtsx.com/ and I don't see the issue there so I guess using `_app` is the fix :rose:

![image](https://user-images.githubusercontent.com/874898/105627522-6d2c0a80-5e8b-11eb-8eaf-cef276775a52.png)

**Comment by mikecann** [comment]
You sir at a total legend. That did it! 

For the current version of Next you ned to use an effect I think:

```
  useEffect(() => {
    setStylesTarget(document.getElementById("styles-target")!);
  }, []);
```

 :)
